export enum ParentRegisterStepEnum{
    EMAIL, 
    OTP,
    PASSWORD,
    ABOUT,
    STUDENT_NAME,
    STUDENT_SCHOOL_LEVEL,
    STUDENT_SUBJECT,
    COURSE_TYPE,
    AVAILABILITY, 
    SUGGESTED_TUTOR
}